/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "../tests/s21_string_tests.check" instead.
 */

#include <check.h>
#include <stdio.h>
#include <stdlib.h>

#include "../src/s21_string.h"
#include "../src/s21_string_extra.h"

START_TEST(test_s21_memchr) {
  char str[] =
      "- Good morning! Help me please! \0 joke by aatroxiv, lenwoodr, "
      "licoricg, "
      "vinephil, livardce \n";
  char ch[] = {'-', 'H', 'l', 'p', '\n'};
  int num[] = {2, 4, 20, 40, 100};

  for (int i = 0; i < 5; i++) {
    ck_assert_ptr_eq(s21_memchr(str, ch[i], num[i]),
                     memchr(str, ch[i], num[i]));

    printf("***debug --->  s21_memchr(str, ch[i], num[i]) = %p, i = %d\n",
           memchr(str, ch[i], num[i]), i);
  }
}
END_TEST

START_TEST(test_s21_memcmp) {
  char str[][30] = {
      "aatroxiv", "aatrox1v", "_aatroxiv", "aatroxi", "aatroxiv_1",
  };
  int num[] = {2, 4, 20, 40, 0};

  for (int i = 0; i < 5; i++) {
    ck_assert_int_eq(s21_memcmp(str[0], str[i], num[i]),
                     memcmp(str[0], str[i], num[i]));
    printf("***debug --->  s21_memcmp(str[0], str[i], num[i]) = %d, i = %d\n",
           s21_memcmp(str[0], str[i], num[i]), i);
  }
}
END_TEST

START_TEST(test_s21_memcpy) {
  char str_1[][30] = {"aatroxiv", "lenwoodr", "licoricg", "vinephil",
                      "livardce"};
  char str_2[][30] = {"aatroxiv", "lenwoodr", "licoricg", "vinephil",
                      "livardce"};
  int num[] = {2, 4, 20, 30, 0};

  for (int i = 0; i < 4; i++) {
    ck_assert_mem_eq(s21_memcpy(str_1[i], str_1[i + 1], num[i]),
                     memcpy(str_2[i], str_2[i + 1], num[i]), 30);
    printf(
        "***debug --->  s21_memcpy(str_1[i], str_1[i+1], num[i]) = %p, i = "
        "%d\n",
        s21_memcpy(str_1[i], str_1[i + 1], num[i]), i);
  }
}
END_TEST

START_TEST(test_s21_memset) {
  char str_1[][30] = {"aatroxiv", "lenwoodr", "licoricg", "vinephil",
                      "livardce"};
  char str_2[][30] = {"aatroxiv", "lenwoodr", "licoricg", "vinephil",
                      "livardce"};
  char ch[] = {'-', 'H', 'l', 'p', '\n'};
  int num[] = {2, 4, 20, 30, 0};

  for (int i = 0; i < 5; i++) {
    ck_assert_mem_eq(s21_memset(str_1[i], ch[i], num[i]),
                     memset(str_2[i], ch[i], num[i]), 30);

    printf(
        "***debug --->  s21_memset(str_1[i], ch[i], num[i]) = %p, i = %d, str "
        "= "
        "%s\n",
        s21_memset(str_1[i], ch[i], num[i]), i, str_1[i]);
  }
}
END_TEST

START_TEST(test_s21_strncat) {
  char str_1[][30] = {"aatroxiv", "lenwoodr", "licoricg", "vinephil",
                      "livardce"};
  char str_2[][30] = {"aatroxiv", "lenwoodr", "licoricg", "vinephil",
                      "livardce"};
  int num[] = {2, 4, 20, 0, 0};

  for (int i = 0; i < 4; i++) {
    ck_assert_mem_eq(s21_strncat(str_1[i], str_1[i + 1], num[i]),
                     strncat(str_2[i], str_2[i + 1], num[i]), 30);

    printf(
        "***debug --->  s21_strncat(str_1[i], str_1[i+1], num[i]) = %p, i = "
        "%d, "
        "str "
        "= "
        "%s\n",
        s21_strncat(str_1[i], str_1[i + 1], num[i]), i, str_1[i]);
  }
}
END_TEST

START_TEST(test_s21_strchr) {
  char str[][30] = {"aatroxiv", "lenwoodr", "licoricg", "vinephil", "livardce"};
  char ch[] = {'\0', 'H', 'l', 'p', '\t'};

  for (int i = 0; i < 5; i++) {
    ck_assert_ptr_eq(s21_strchr(str[i], ch[i]), strchr(str[i], ch[i]));

    printf(
        "***debug --->  s21_strchr(str[i], ch[i]) = %p, i = %d, ch= %c, str = "
        "%s\n",
        s21_strchr(str[i], ch[i]), i, ch[i], s21_strchr(str[i], ch[i]));
  }
}
END_TEST

START_TEST(test_s21_strncmp) {
  char str[][30] = {
      "aatroxiv", "aatrox1v", "_aatroxiv", "aatroxi", "aatroxiv_1",
  };
  int num[] = {2, 4, 20, 40, 0};

  for (int i = 0; i < 5; i++) {
    ck_assert_int_eq(s21_strncmp(str[0], str[i], num[i]),
                     strncmp(str[0], str[i], num[i]));
    printf("***debug --->  s21_strncmp(str[0], str[i], num[i]) = %d, i = %d\n",
           s21_strncmp(str[0], str[i], num[i]), i);
  }
}
END_TEST

START_TEST(test_s21_strncpy) {
  char str_1[][30] = {"aatroxiv", "lenwoodr", "licoricg", "vinephil",
                      "livardce"};
  char str_2[][30] = {"aatroxiv", "lenwoodr", "licoricg", "vinephil",
                      "livardce"};
  int num[] = {2, 4, 20, 30, 0};

  for (int i = 0; i < 4; i++) {
    ck_assert_mem_eq(s21_strncpy(str_1[i], str_1[i + 1], num[i]),
                     strncpy(str_2[i], str_2[i + 1], num[i]), 30);
    printf(
        "***debug --->  s21_strncpy(str_1[i], str_2[i+1], num[i]) = %p, i = "
        "%d\n",
        s21_strncpy(str_1[i], str_1[i + 1], num[i]), i);
  }
}
END_TEST

START_TEST(test_s21_strcspn) {
  char str[][30] = {"aatroxiv", "lenwoodr", "_icoricg", "vinephi", "_ivardce"};

  for (int i = 0; i < 4; i++) {
    ck_assert_int_eq(s21_strcspn(str[i], str[i + 1]),
                     strcspn(str[i], str[i + 1]));
    printf("***debug --->  s21_strcspn(str[i], str[i+1]) = %ld, i = %d\n",
           s21_strcspn(str[i], str[i + 1]), i);
  }
}
END_TEST

START_TEST(test_s21_strerror) {
  for (int i = 0; i < 134; i += 1) {
    ck_assert_str_eq(s21_strerror(i), strerror(i));

    printf("***debug --->  s21_strerror(i) = %s, i = %d\n", s21_strerror(i), i);
  }

  for (int i = -10; i < 140; i += 1) {
    if (i > 3 && i < 130) continue;
    printf("___***debug --->  s21_strerror(i) = \"%s\", i = %d\n",
           s21_strerror(i), i);
    printf("___***debug --->      strerror(i) = \"%s\", i = %d\n", strerror(i),
           i);
  }
}
END_TEST

START_TEST(test_s21_strlen) {
  char str_array[][20] = {"Privet mir", "Privet \t\n", "\0", "",
                          "Privet \0 MIR"};

  for (int i = 0; i < 5; i++) {
    ck_assert_int_eq(s21_strlen(str_array[i]), strlen(str_array[i]));
    printf("***debug --->  s21_strlen(str_array[%d]) %lu\n", i,
           s21_strlen(str_array[i]));
  }
}
END_TEST

START_TEST(test_s21_strpbrk) {
  char str[][30] = {"aatroxiv", "lenwoodr", "_icoricg", "vinephi", "aaaaaaa"};

  for (int i = 0; i < 4; i++) {
    ck_assert_ptr_eq(s21_strpbrk(str[i], str[i + 1]),
                     strpbrk(str[i], str[i + 1]));
    printf("***debug --->  s21_strpbrk(str[i], str[i+1]) = %p, i = %d\n",
           s21_strpbrk(str[i], str[i + 1]), i);
  }
}
END_TEST

START_TEST(test_s21_strrchr) {
  char str[][30] = {"aatroxiv", "lenwoodr", "licoricg", "vinephil", "livardce"};
  int num[] = {0, 72, 108, 112, 9};

  for (int i = 0; i < 5; i++) {
    ck_assert_ptr_eq(s21_strrchr(str[i], num[i]), strrchr(str[i], num[i]));

    printf(
        "***debug --->  s21_strrchr(str[i], num[i]) = %p, i = %d, ch= %c, str "
        "= "
        "%s\n",
        s21_strrchr(str[i], num[i]), i, num[i], s21_strrchr(str[i], num[i]));
  }
}
END_TEST

START_TEST(test_s21_strstr) {
  char src[] =
      "- Good morning! Help me please! \n joke by aatroxiv, lenwoodr, "
      "licoricg, "
      "vinephil, livardce";
  char str[][30] = {"aatroxiv", "lenwoodr", "licoricg", "vinephil", "livardce"};

  for (int i = 0; i < 5; i++) {
    ck_assert_ptr_eq(s21_strstr(src, str[i]), strstr(src, str[i]));

    printf("***debug --->  s21_strstr(src,str[i]) = %p, i = %d, str = %s\n",
           s21_strstr(src, str[i]), i, s21_strstr(src, str[i]));
  }
}
END_TEST

START_TEST(test_s21_strtok) {
  char src[] =
      "- Good morning! Help me please! joke by aatroxiv, lenwoodr, licoricg, "
      "vinephil, livardce";
  int length = s21_strlen(src);

  char src_1[length + 1], src_2[length + 1];
  strcpy(src_1, src);
  strcpy(src_2, src);

  char delim[] = " ,.-!";

  char *res_1 = s21_strtok(src_1, delim);
  char *res_2 = strtok(src_2, delim);

  while (res_1 && res_2) {
    ck_assert_str_eq(res_1, res_2);
    printf(
        "***debug in while --->  s21_strtok(src_1, delim) = %p, res = |%s|\n"
        "***debug in while --->  strtok(src_2, delim) = %p, res = |%s|\n",
        res_1, res_1, res_2, res_2);
    res_1 = s21_strtok(S21_NULL, delim);
    res_2 = strtok(NULL, delim);
  }
  ck_assert_ptr_eq(res_1, res_2);

  printf(
      "***debug --->  s21_strtok(src_1, delim) = %p\n"
      "***debug --->  strtok(src_2, delim) = %p \n",
      res_1, res_2);

  res_1 = s21_strtok(S21_NULL, delim);
  res_2 = strtok(NULL, delim);
  ck_assert_ptr_eq(res_1, res_2);

  printf(
      "***debug --->  s21_strtok(src_1, delim) = %p\n"
      "***debug --->  strtok(src_2, delim) = %p \n",
      res_1, res_2);
}
END_TEST

START_TEST(test_s21_to_upper) {
  char src_1[] = "qwertyuiopasdfghjklzxcvbnm[];',./";
  char src_2[] =
      " !\"#$%&'()*+,-./"
      "0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_`"
      "abcdefghijklmnopqrstuvwxyz{|}~";

  char expected_1[] = "QWERTYUIOPASDFGHJKLZXCVBNM[];',./";
  char expected_2[] =
      " !\"#$%&'()*+,-./"
      "0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_`"
      "ABCDEFGHIJKLMNOPQRSTUVWXYZ{|}~";

  char *str_after_s21_to_upper_1 = s21_to_upper(src_1);

  if (str_after_s21_to_upper_1) {
    ck_assert_str_eq(expected_1, str_after_s21_to_upper_1);
    printf("***debug --->  s21__to_upper(str_after_s21_to_upper_1) = %s\n",
           str_after_s21_to_upper_1);
    free(str_after_s21_to_upper_1);
  }

  char *str_after_s21_to_upper_2 = s21_to_upper(src_2);
  if (str_after_s21_to_upper_2) {
    ck_assert_str_eq(expected_2, str_after_s21_to_upper_2);

    printf("***debug --->  s21__to_upper(str_after_s21_to_upper_2) = %s\n",
           str_after_s21_to_upper_2);

    free(str_after_s21_to_upper_2);
  }
}
END_TEST

START_TEST(test_s21_to_lower) {
  char src_1[] = "QWERTYUIOPASDFGHJKLZXCVBNM[];',./";
  char src_2[] =
      " !\"#$%&'()*+,-./"
      "0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_`"
      "abcdefghijklmnopqrstuvwxyz{|}~";

  char expected_1[] = "qwertyuiopasdfghjklzxcvbnm[];',./";
  char expected_2[] =
      " !\"#$%&'()*+,-./"
      "0123456789:;<=>?@abcdefghijklmnopqrstuvwxyz[]^_`"
      "abcdefghijklmnopqrstuvwxyz{|}~";

  char *str_after_s21_to_lower_1 = s21_to_lower(src_1);
  if (str_after_s21_to_lower_1) {
    ck_assert_str_eq(expected_1, str_after_s21_to_lower_1);

    printf("***debug --->  s21__to_lower(str_after_s21_to_lower_1) = %s\n",
           str_after_s21_to_lower_1);
    free(str_after_s21_to_lower_1);
  }

  char *str_after_s21_to_lower_2 = s21_to_lower(src_2);
  if (str_after_s21_to_lower_2) {
    ck_assert_str_eq(expected_2, str_after_s21_to_lower_2);

    printf("***debug --->  s21__to_lower(str_after_s21_to_lower_2) = %s\n",
           str_after_s21_to_lower_2);

    free(str_after_s21_to_lower_2);
  }
}
END_TEST

START_TEST(test_s21_insert) {
  char *src_1 = "aatroxiv, lenwoodr, licoricg, vinephil, livardce";
  char *src_2 = "Insert into __ here!";

  char *str_1 = "Hello! It is ";
  char *str_2 = "OK";

  char *expected_1 =
      "Hello! It is aatroxiv, lenwoodr, licoricg, vinephil, livardce";
  char *expected_2 = "Insert into _OK_ here!";

  char *res_1 = s21_insert(src_1, str_1, 0);
  printf("***debug ---> char* res_1 = s21_insert(str_1, src_1, 0) = %s\n",
         res_1);

  if (res_1) {
    ck_assert_str_eq(res_1, expected_1);
    printf("***debug --->  s21__insert(src_1, str_1, 0) = %s\n", res_1);
    free(res_1);
  }

  char *res_2 = s21_insert(src_2, str_2, 13);
  printf("***debug ---> char* res_2 = s21_insert(src_2, str_2, 13) = %s\n",
         res_2);

  if (res_2) {
    ck_assert_str_eq(res_2, expected_2);
    printf("***debug --->  s21__insert(src_2, str_2, 0) = %s\n", res_2);
    free(res_2);
  }
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, test_s21_memchr);
  tcase_add_test(tc1_1, test_s21_memcmp);
  tcase_add_test(tc1_1, test_s21_memcpy);
  tcase_add_test(tc1_1, test_s21_memset);
  tcase_add_test(tc1_1, test_s21_strncat);
  tcase_add_test(tc1_1, test_s21_strchr);
  tcase_add_test(tc1_1, test_s21_strncmp);
  tcase_add_test(tc1_1, test_s21_strncpy);
  tcase_add_test(tc1_1, test_s21_strcspn);
  tcase_add_test(tc1_1, test_s21_strerror);
  tcase_add_test(tc1_1, test_s21_strlen);
  tcase_add_test(tc1_1, test_s21_strpbrk);
  tcase_add_test(tc1_1, test_s21_strrchr);
  tcase_add_test(tc1_1, test_s21_strstr);
  tcase_add_test(tc1_1, test_s21_strtok);
  tcase_add_test(tc1_1, test_s21_to_upper);
  tcase_add_test(tc1_1, test_s21_to_lower);
  tcase_add_test(tc1_1, test_s21_insert);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
